# Generated by Django 3.0.5 on 2021-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bearer_In',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Opérateur', models.CharField(max_length=255)),
                ('GTPv2_C_Attempts_IN', models.IntegerField()),
                ('GTPv2_C_Failures_IN', models.IntegerField()),
                ('GTPv2_C_Failure_IN', models.FloatField()),
                ('GTPv2_C_Average_Latency_msec_IN', models.FloatField()),
                ('GTPv2_C_Average_Session_Duration_msec_IN', models.CharField(max_length=255)),
                ('Efficacité_IN', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Bearer_Out',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=255)),
                ('Opérateur', models.CharField(max_length=255)),
                ('GTPv2_C_Attempts_OUT', models.IntegerField()),
                ('GTPv2_C_Failures_OUT', models.IntegerField()),
                ('GTPv2_C_Failure_OUT', models.FloatField()),
                ('GTPv2_C_Average_Latency_msec_OUT', models.FloatField()),
                ('GTPv2_C_Average_Session_Duration_msec_OUT', models.CharField(max_length=255)),
                ('Efficacité_OUT', models.FloatField()),
            ],
        ),
    ]
