# Generated by Django 3.1.5 on 2021-02-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.CharField(max_length=100)),
                ('files', models.FileField(upload_to='files')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
