# Generated by Django 3.1.5 on 2021-02-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Type',
            field=models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], default='IN', max_length=20),
            preserve_default=False,
        ),
    ]
