# Generated by Django 3.1.5 on 2021-02-11 20:36

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0002_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(upload_to='', verbose_name=django.db.models.expressions.When(fileName='SAI', upload_to='zakari')),
        ),
    ]
