# Generated by Django 3.1.5 on 2021-02-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0003_auto_20210211_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(upload_to=models.CharField(max_length=100)),
        ),
    ]
