# Generated by Django 3.1.5 on 2021-02-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0004_auto_20210211_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(upload_to='files'),
        ),
    ]
