# Generated by Django 3.1.5 on 2021-02-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0008_auto_20210215_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(upload_to='files/<django.db.models.fields.CharField>/'),
        ),
    ]
