# Generated by Django 3.0.5 on 2021-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0009_auto_20210215_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='files',
            field=models.FileField(upload_to='files'),
        ),
    ]
