# Generated by Django 3.1.3 on 2021-03-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('alpha3Code', models.CharField(max_length=255)),
                ('callingCodes', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('flag', models.URLField(max_length=255)),
            ],
        ),
    ]
