# Generated by Django 3.0.5 on 2021-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sai_out',
            name='EFF',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sai_out',
            name='Failed_Transactions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sai_out',
            name='Total_Transactions',
            field=models.IntegerField(),
        ),
    ]
