# Generated by Django 3.0.5 on 2021-02-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sai', '0002_auto_20210219_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sai_out',
            name='Direction',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sai_out',
            name='HVA',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sai_out',
            name='Interval_Time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sai_out',
            name='Opcode',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sai_out',
            name='PLMN_Carrier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sai_out',
            name='Service',
            field=models.CharField(max_length=255),
        ),
    ]
