# Generated by Django 3.1.5 on 2021-03-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdp_in',
            name='GTP_C_Procedure_Average_Latency_msec_IN',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='pdp_out',
            name='GTP_C_Procedure_Average_Latency_msec',
            field=models.FloatField(null=True),
        ),
    ]
